### ISSUE TITLE
Bluetooth non-LE detection

### ISSUE THREAD

**Issue by dlashua** [zewelor/bt-mqtt-gateway#105]
**Is your feature request related to a problem? Please describe.**
I don't know all the bluetooth wording, so forgive me if I'm using the wrong descriptions for things.

I have several bluetooth LE devices that blescanmulti picks up perfectly. However, I have a few devices that don't do BLE broadcast/announcements. They are available in the "old" bluetooth manner, in the same way you'd connect to bluetooth speakers and such. And I would like to detect them.

Using bluetoothctl I can see them in a scan just fine. But, adding them to the blescanmulti config, they are never detected by bt-mqtt-gateway.

Is there already a feature to detect a device like this?

**Describe the solution you'd like**
To detect available "regular" bluetooth devices. 

**Describe alternatives you've considered**
Running bt-mqtt-gateway to handle all the things it does, and running a separate gateway on another bluetooth device just to detect devices like this.

**Additional context**
In particular, a device I'm trying to detect is a One Plus 6T Mobile Phone.

**Comment by cichy63** [comment]
Hi,

i would be interested in this feature as well (detecting smartphone BT, not BLE). Is it possible?
