### ISSUE TITLE
Docker container fails because it can't find sudo and hciconfig

### ISSUE THREAD

**Issue by koenvervloesem** [zewelor/bt-mqtt-gateway#115]
**Describe the bug**
When I build my own Docker image for bt-mqtt-gateway, it fails to start because it doesn't find the `sudo` and `hciconfig` commands.

**To Reproduce**
1. `docker build -t bt-mqtt-gateway -f Dockerfile`
2. Create config file.
3. Run Docker container
4. See error "/bin/sh: sudo: not found" in output of `docker logs bt-mqtt-gateway`.

**Expected behavior**
The container starts correctly.

**Server (please complete the following information):**
 - OS: Linux
 - Distro: Ubuntu
 - Version: 19.10

The same happens on Raspbian Buster Lite on a Raspberry Pi 3B+ when I build and run the arm32v7 container image.

**Additional context**
When I add `sudo` to the last `apk add` line in the Dockerfile and rebuild the image, the container again gives an error message, this time complaining that it can't find `hciconfig`.

When I add `bluez-deprecated` to the last `apk add`line, the rebuilt image works correctly.

**Comment by zewelor** [comment]
Which workers are you using ?

**Comment by koenvervloesem** [comment]
miflora and ruuvitag

**Comment by koenvervloesem** [comment]
I still have this bug with your newest official build from https://hub.docker.com/r/zewelor/bt-mqtt-gateway/builds (commit 01734db)

**Comment by koenvervloesem** [comment]
I investigated further: I definitely needed to add the `sudo` and `bluez-deprecated` packages to the Docker container in my RuuviTag pull request https://github.com/zewelor/bt-mqtt-gateway/pull/112

The ruuvitag-sensor package is being refactored to using Bleson instead of Bluez, so maybe in the future this isn't needed anymore: https://github.com/ttu/ruuvitag-sensor/issues/78

Can you add the packages to the Dockerfiles or do I file a pull request?

**Comment by zewelor** [comment]
That make sense. Most worker's doesn't need that, so probably nooone, using
docker, had that problem before. Only that 2 packages are needed to be add
in docker file to make it work?

**Comment by koenvervloesem** [comment]
Yes with only those two packages added the ruuvitag worker works in Docker. I'm using it successfully in this project: https://github.com/koenvervloesem/ruuvitag-demo
