### ISSUE TITLE
Empty values on restart of Homeassistant with current service file

### ISSUE THREAD

**Issue by schneekluth** [zewelor/bt-mqtt-gateway#13]
Hello,

your gateway is awesome. I've only found one little issue. Whenever I reboot my system the linked MQTT-Sensors in Homeassistant remain empty for the duration of the specified `update_intervall`. It seems that bt-mqtt-gateeway is loaded before Mosquitto broker and Homeassistant are running. Maybe you could adjust the service file to start the gateway only if the broker and Homeassistant are running. I currently don't know how to do this. Maybe with `Require=x` or `After=x`?

**Comment by bbbenji** [comment]
I don't think `Requires=x` or `After=x` are viable here. Not everyone is running an MQTT broker on the same device. Perhaps `Wants=X` or `Type=idle` is the solution.

**Comment by zewelor** [comment]
@schneekluth Gateway should auto update all sensors when HA start / restart. I've updated Wiki with required mqtt component settings for Home assistant. Take a look here https://github.com/zewelor/bt-mqtt-gateway/wiki/Home-Assistant#home-assistant-mqtt-config you need to have birth message with that settings, they are the same as defined in gateway's config ( https://github.com/zewelor/bt-mqtt-gateway/blob/master/config.yaml.example ). if you want to change them, update config.yaml accordingly. After Home assistant changes restart it, and now after each start gateway you force update all sensors, regardless of last update time / defined update interval

**Comment by schneekluth** [comment]
@zewelor Oh, Pardon. I've missed that Part. Thanks for your quick answer.

**Comment by zewelor** [comment]
@schneekluth You did not miss it. I've added that info after this issue, because it was clearly missing :D

**Comment by schneekluth** [comment]
@zewelor Pardon again. I've missed that I did not have missed it. :) It's running fine now.
