### ISSUE TITLE
Docker Compose Volumes

### ISSUE THREAD

**Issue by xMrVizzy** [zewelor/bt-mqtt-gateway#130]
Please tell me how I can connect config.yaml file in local folder to docker container? Like MOSQUITTO!

<img width="386" alt="CleanShot 2020-01-02 at 00 36 44@2x" src="https://user-images.githubusercontent.com/7906418/71645293-f8be8080-2cf7-11ea-8330-d3f24cf82791.png">

**Comment by koenvervloesem** [comment]
config

**Comment by xMrVizzy** [comment]
yes I find a way!

<img width="358" alt="CleanShot 2020-01-02 at 00 45 43@2x" src="https://user-images.githubusercontent.com/7906418/71645370-37a10600-2cf9-11ea-857b-c66c9486ba00.png">

**Comment by xMrVizzy** [comment]
But now I have error in logs! 

<img width="761" alt="CleanShot 2020-01-02 at 00 46 18@2x" src="https://user-images.githubusercontent.com/7906418/71645377-4be50300-2cf9-11ea-8565-1a4b7b8f13b9.png">

**Comment by koenvervloesem** [comment]
Your container needs the right permissions.

See https://github.com/koenvervloesem/ruuvitag-demo/blob/master/docker-compose.yml for an example.

**Comment by xMrVizzy** [comment]
Thank you, all work now!

**Comment by xMrVizzy** [comment]
@koenvervloesem #131 help please if you know!
