### ISSUE TITLE
Custom Worker over Docker Compose

### ISSUE THREAD

**Issue by xMrVizzy** [zewelor/bt-mqtt-gateway#131]
Is it possible to add Custom Worker python file over Docker Compose Volume?

**Comment by koenvervloesem** [comment]
I wouldn't do this. If it's for testing a new worker, better test it in a venv, or create your own Docker image with `docker build` that includes the new worker file.

**Comment by xMrVizzy** [comment]
How I can make a build from local folder using Docker Compose?

**Comment by koenvervloesem** [comment]
Just do a `docker build . -t tagyouwanttouse`.

**Comment by xMrVizzy** [comment]
ok, thanks!
