### ISSUE TITLE
Feature request: Set LINAK desk height

### ISSUE THREAD

**Issue by mountainsandcode** [zewelor/bt-mqtt-gateway#138]
**Is your feature request related to a problem? Please describe.**
Thanks for an awesome project for checking the height of a LINAK desk. It would be great to also control the height of it, i.e. sending an MQTT request with a specific height that is then transferred to the bluetooth controller

**Describe the solution you'd like**
An MQTT topic listening for a specific height of the LINAK desk using https://github.com/zewelor/linak_bt_desk/blob/master/linak_dpg_bt/desk_mover.py

**Describe alternatives you've considered**
None

**Comment by zewelor** [comment]
Whats use case for that ? Does it make sense to control height, when not near the desk ?

I've didn't implement it on purpose as it looks dangerous ( like forgot that something is below / on desk etc ). And on some gateway error / code error / etc, it will move on its own, that can cause trouble. Desk has some option to don't crush something, but from my tests it needs to be something very hard, it still can do damage.

**Comment by mountainsandcode** [comment]
Valid concern!
I was thinking of using it when at the desk, simply using it to get the desk (which doesn't have memory buttons itself - the IKEA one) to a predefined height.

In my specific case, I was thinking of using Home Assistant to help me to raise it to my specific standing height when I want to stand up (perhaps even using Siri through the HomeKit bridge).

**Comment by zewelor** [comment]
Do you have ikea desk or some other with LINAK controller ? Which Linak controller is it ?

**Comment by mountainsandcode** [comment]
I'll be picking up a IKEA IDÅSEN standing desk next week, which uses the DPG1M LINAK controller (according to https://www.workwhilewalking.com/ikea-idasen-standing-desk-underframe-review it's a derivate of the DPG1C)

**Comment by zewelor** [comment]
I've got the same controller, and it has height memory. You just make double click up or down, it has 2 height slots memory. https://www.youtube.com/watch?v=63SpX9EZWD0

**Comment by mountainsandcode** [comment]
Excellent news - I guess I was wrongly extrapolating from the old IKEA desk I know which doesn't have a LINAK. Let's consider this a low priority in that case!

**Comment by noxhirsch** [comment]
@zewelor The IKEA Idasen controller does not have auto drive (LINAK also confirmed that under a video tutorial by them)! You can save heights in the app but you have to keep the button pressed. 
If the height could be set with this gateway you could start moving the desk and do something else until it finished and don't have to stand besides it keeping the button pressed. Or you could start the heigth change from another room and it has finished when you arrive at the desk.

**Comment by redparchel** [comment]
recently received my Ikea Idasen, looks like they no longer use a controller that supports auto drive (or memory recalled via the switch). 

(I'm WFH full time at the moment and) I would love for my desk to raise to the right height (no matter where I left it) as part of my "good morning" automatons (i like to stand in the morning)

That also said, i did buy a replacement controller (the switch not the control box) on amazon that has autodrive and memory. so I'd be happy with memory recall. my goal of using homeassistant is to reduce the number of extra apps i need to control my home. 
thanks!
-rich
