### ISSUE TITLE
Addendum to Virtualenv installation instructions

### ISSUE THREAD

**Issue by leopold005** [zewelor/bt-mqtt-gateway#162]
I'm installing the gateway on a brand new Pi Zero W with Raspbian Buster Lite and I get all manner of installation errors when trying to run the first command.  After some digging, I found the fix by running the following commands prior to running yours:

```
sudo apt-get update
sudo apt-get dist-upgrade
sudo apt-get install git
sudo apt-get clean
```
This appears to have fixed the issue (or at least it has until the virtualenv command!)

**Comment by zewelor** [comment]
Right git is needed for miflora. Thanks for looking into this ! Added to readme
