### ISSUE TITLE
Installation issue at virtualenv command 

### ISSUE THREAD

**Issue by leopold005** [zewelor/bt-mqtt-gateway#164]
When I get to this command (installing on Pi Zero W with Raspbian Buster Lite):

`virtualenv -p python3 .venv`

I get an error telling me that virtualenv isn’t a valid command. Which I don’t quite understand as it looked like it had installed cleanly.  I’m a bit of a noob to this Linux thing, so any help would be very much appreciated.

**Comment by Yvon-Indel** [comment]
Hi,

I've got the same message on raspi1 and did this command : `python3 -m virtualenv .venv`

**Comment by leopold005** [comment]
Thanks, that nailed it!
