### ISSUE TITLE
ModuleNotFoundError: No module named 'apscheduler'

### ISSUE THREAD

**Issue by willsy555** [zewelor/bt-mqtt-gateway#183]
Hi zewelor,

Thank you very much for this Gateway facility. Been looking for something like this for quite some time and it will potentially keep my dining room plants very happy. ;-)

Only problem is that I can run this manually without issue, but don't get any results when running it as a service. It's installed on a Raspberry Pi Zero W with the latest Raspbian minimal.

If I check the journal, I can see an error in there referring to  ModuleNotFoundError: No module named 'apscheduler'

May 29 22:56:35 raspberrypi service.sh[1490]: Traceback (most recent call last):
May 29 22:56:35 raspberrypi service.sh[1490]:   File "./gateway.py", line 21, in <module>
May 29 22:56:35 raspberrypi service.sh[1490]:     from workers_manager import WorkersManager
May 29 22:56:35 raspberrypi service.sh[1490]:   File "/home/pi/bt-mqtt-gateway/workers_manager.py", line 7, in <module>
May 29 22:56:35 raspberrypi service.sh[1490]:     from apscheduler.schedulers.background import BackgroundScheduler
May 29 22:56:35 raspberrypi service.sh[1490]: ModuleNotFoundError: No module named 'apscheduler'
May 29 22:56:35 raspberrypi systemd[1]: bt-mqtt-gateway.service: Main process exited, code=exited, status=1/FAILURE

If I try running the requirements txt, everything seems to be satisifed:

pi@raspberrypi:~/bt-mqtt-gateway $ sudo pip3 install -r requirements.txt
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: paho-mqtt in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 1)) (1.5.0)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 2)) (5.3.1)
Requirement already satisfied: interruptingcow in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 3)) (0.8)
Requirement already satisfied: apscheduler in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 4)) (2.1.2)

Not sure what the problem could be and wondered if you could help? Would be great to get this up and running properly! :-)

Thanks

Will

**Comment by zewelor** [comment]
Are you running gateway from service as root user ? Maybe try to add .venv dir in gateway and restart service, it should install requirements as virtual env.

**Comment by willsy555** [comment]
Thanks zewelor. That didn't work so tried the following which has resolved the issue. Not exactly what is the exact cause of the problem though!

1) re-flashed the latest version of raspbian lite onto the micro sd.
2) enabled the root user and login as root for all activities.
3) updated all pacakges to be sure.
4) followed your installation guide. Instead removing sudo from all commands though.
5) when following the installation guide, don't run this step until the config.yaml has been initially been setup:
$ pip3 install `./gateway.py -r configured` 

Hope this helps someone! :-)

Must say again zewelor, what a cool little gatway application you have made. Thank you!! 👍 :-)

Cheers 

Will.

**Comment by zewelor** [comment]
Thanks, greats it working !
