### ISSUE TITLE
Please add to debug-wiki page how to enable Debug in Docker

### ISSUE THREAD

**Issue by GrumpyMeow** [zewelor/bt-mqtt-gateway#191]
# My suggested change is hereunder:

To run bt-mqtt-gateway in debug mode

`sudo ./gateway.py -d`

To check systemd service logs

`journalctl -xef -u bt-mqtt-gateway`

Viewing MQTT messages

`mosquitto_sub -h localhost -d -t '#'`

To run bt-mqtt-gateway in a Docker container in debug mode

add environment parameter `-e DEBUG=true`

or in Docker-compose:

```
environment:
- DEBUG=true
```

**Comment by zewelor** [comment]
Added thanks ! https://github.com/zewelor/bt-mqtt-gateway/wiki/Debug
