### ISSUE TITLE
do thermostats show up as thermostats in hass

### ISSUE THREAD

**Issue by snizzleorg** [zewelor/bt-mqtt-gateway#21]
Hi,

this looks very promising but before I drop the money on a few rpi-zeros to connect my eq3bt thermostats to home-assistant via this gateway I would like to ask whether the thermostats do show up as climate components in hass?

**Comment by disrupted** [comment]
sorry to hijack this thread but is it possible to see the current valve position (as with the default [eq3btsmart integration](https://www.home-assistant.io/components/climate.eq3btsmart/)) within Home Assistant using this gateway?

**Comment by zewelor** [comment]
@disrupted Yes it returns valve_state and other attributes.

```
thermostat/livingroom/away off
thermostat/livingroom/mode auto
thermostat/livingroom/locked False
thermostat/livingroom/window_open False
thermostat/livingroom/target_temperature 20.0
thermostat/livingroom/valve_state 18
thermostat/livingroom/low_battery False
```

just add mqtt sensor for desired topic

**Comment by disrupted** [comment]
@zewelor awesome, thanks !
