### ISSUE TITLE
error on gateway.py

### ISSUE THREAD

**Issue by jumping2000** [zewelor/bt-mqtt-gateway#23]
Hi,
I have this error on raspberry Pi Zero W with last Raspbian Strech Lite, is there a way to solve it?
thanks

```
./gateway.py
Traceback (most recent call last):
  File "./gateway.py", line 15, in <module>
    from workers_manager import WorkersManager
  File "/home/pi/bt-mqtt-gateway/workers_manager.py", line 4, in <module>
    from pip._internal import main as pip_main
ImportError: No module named 'pip._internal'
```

**Comment by zewelor** [comment]
From fast google search:
https://github.com/pypa/pip/issues/5373
https://github.com/pypa/pip/issues/5253

Are you using python 3 ?

**Comment by jumping2000** [comment]
hello, thank you for your answer!
before writing here I searched on google but the problem it'a a little bit different because Phyton and Pip appear to be good:

```
pi@raspberrypi:~/bt-mqtt-gateway $ pip3 -V
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.5)
```
```
pi@raspberrypi:~/bt-mqtt-gateway $ python3 --version
Python 3.5.3
```

**Comment by bbbenji** [comment]
What is the output of `pip -V`?

If it's an unknown command, you can either add an alias to your ~/.bashrc

    alias pip=pip3

or add to your $PATH symlink named pip pointing to the pip3 binary.

**Comment by jumping2000** [comment]
now after "pip install --upgrade pip" I have another type of error

**Comment by bbbenji** [comment]
pip install python-eq3bt

**Comment by jumping2000** [comment]
Great!! Now it works:
./gateway.py -d
```
Starting
Added: miflora with 600 seconds interval
Added: thermostat with 120 seconds interval
Subscribing to: thermostat/+/+/set
Subscribing to: homeassistant/status with command: update_all
Updating all workers
```
So, do you understand what was the problem?
I see in closed issues that there is not error with python 3.6 , maybe with python 3.5 do I need to upgrade pip (with pip install --upgrade pip) ?
bye

**Comment by bbbenji** [comment]
I think the error was that you had pip on Python 2.x and pip3 on Python 3.x. Then the second error was just missing `python-eq3bt`. Glad you got it working:)
