### ISSUE TITLE
use bt-mqtt-gateway with standard Raspbian Strech 

### ISSUE THREAD

**Issue by jumping2000** [zewelor/bt-mqtt-gateway#24]
hi,
some days ago I had some problems with the gateway, I will write here the solution suitable for me :

- the bt-mqtt-gateway was developed with Python 3.6 and use Pip with version>10
- Raspbian Stretch comes wit Python 3.5.3 and Pip 9.01
- upgrade Python is not fast with Pi Zero
- upgrade only pip with commands like " pip install --upgrade" is not recommended  and takes lot of problems (see https://github.com/pypa/pip/issues/5599)
SOLUTION:
I changed line 4 and 98 of workers_manager.py  with this code:
- (4) `from pip import main`
- (98) `main(['install', '-q', package])`

now the bt-mqtt-gateway  works well with my Pi Zero W with last DietPi distribution (based on Stretch).
Bye

**Comment by hobbypunk90** [comment]
and than bt-mqtt-gateway only works with pip < 10.0 😉
better solution is a switch for older pip versions 😁

**Comment by jumping2000** [comment]
well done, my solution was a work-around, I'm not a programmer :-) 
bye
