### ISSUE TITLE
Docker images Exited (139)

### ISSUE THREAD

**Issue by Smandurlo** [zewelor/bt-mqtt-gateway#245]
[x] I've read the [Troubleshooting Wiki](https://github.com/zewelor/bt-mqtt-gateway/wiki/Troubleshooting), my problem is not described there and I am  already using the specified minimum bluez version.

**Describe the bug**
I am not really able to run the docker /docker-compose version. They were running flawless on 2 raspberry pi zero w, one with buster and another one with bulleye.
This morning I decided to make a clean installation from scratch (to upgrade buster and reclaim 10GB wasted space on bulleye), just installed docker and docker-compose, copied the same config.yaml and docker-compose.yaml but I get Exited (139).

The log is empy. Debug is true.

**To Reproduce**
1. Install docker
2. run the command in the wiki
3. check the status with docker ps -a
4. the container Exited (139) and restarting

**Expected behavior**
To have a running container

**Config**
docker run -d --name bt-mqtt-gateway --network=host --cap-add=NET_ADMIN --cap-add=NET_RAW -v $PWD/config.yaml:/application/config.yaml zewelor/bt-mqtt-gateway

**Debug gateway logs**
run gateway.py with -d switch and paste formatted output log

No log, it is empty

**Server (please complete the following information):**
 - OS: raspberry pi os 
 - Distro: raspberry pi os
 - Version: buster and bulleye

**Additional context**

I tried to return to buster, pulled previous images, tried a docker downgrade with no luck.

EDIT: I think I narrowed down the problem. It seems the arm v6 for raspberry pi zero W is no longer there, only v7. I tried with a raspberry pi3 b and it worked immediately without problems.

**Comment by Smandurlo** [comment]
SOLVED: I created a new image from Dockerfile and uploaded to https://hub.docker.com/r/smanny/bt-mqtt-gateway
It is only arm/v6
I hope the next images will be created with v6 included

**Comment by zewelor** [comment]
Thanks for looking into this. Added arm/v6 target https://github.com/zewelor/bt-mqtt-gateway/blob/master/.github/workflows/docker_build.yml#L48
