### ISSUE TITLE
Docker configure.yaml

### ISSUE THREAD

**Issue by schlindw** [zewelor/bt-mqtt-gateway#264]
Hello,

on hub.docker.com there is a problem with the example docker command that starts the container:
`docker run -d --name bt-mqtt-gateway --network=host -v $PWD/config.yaml:/config.yaml zewelor/bt-mqtt-gateway`

The config file is expected under /application/config.yaml, therefore the called command should be:
`docker run -d --name bt-mqtt-gateway --network=host -v $PWD/config.yaml:/application/config.yaml zewelor/bt-mqtt-gateway`

Best regards,
Georg

**Comment by zewelor** [comment]
Thanks ! Looks like readme was not updated, after auto building was disabled on duckerhub.
