### ISSUE TITLE
New worker, Search for BT LE tag

### ISSUE THREAD

**Issue by mredone** [zewelor/bt-mqtt-gateway#28]
New idea.
Add new worker to search specific BT LE tag mac address and send it via mqtt as presence detection HOME/AWAY.

Now i use [room-assistant](https://github.com/mKeRix/room-assistant) on RPi0W with home assistant.
It send a lot information about BLE TAG (i have cheap iTAG).
For presence we need only a is a specific mac in range.
For not flooding mqtt broker it will check is any change and change is send to broker.

**Comment by bbbenji** [comment]
Great idea:) looking forward to your PR!

**Comment by mredone** [comment]
> Great idea:) looking forward to your PR!

Yeah. I can test, i can help but my coding is soooo lame :)

**Comment by zewelor** [comment]
@mredone after merging this is should be supported: https://github.com/zewelor/bt-mqtt-gateway/commit/345b200113bbcc8cc5459f6bb7f3f3cd8e883b11.
