### ISSUE TITLE
sending commands to thermostat

### ISSUE THREAD

**Issue by Damontir** [zewelor/bt-mqtt-gateway#33]
hi,
sorry for the dumb question...

i use 4 eq3 thermostats and want to control them via mqtt
now im curiouse about how to send commands over mqtt to the thermostat.
in the config.yaml is topic_subscription: thermostat/+/+/set and i tryed a lot of commands but nothing worked and i cant find description to this topic.

Whats wrong here?
Thanks in advanced

**Comment by bbbenji** [comment]
Have you taken a look at the wiki: https://github.com/zewelor/bt-mqtt-gateway/wiki/Home-Assistant#eq3-bluetooth-smart-thermostat

**Comment by Damontir** [comment]
Thanks!
