### ISSUE TITLE
How can i now when hostname is offline

### ISSUE THREAD

**Issue by danielaradu2016** [zewelor/bt-mqtt-gateway#40]
Buenas noche. primero queria mucho agradecerlo para el grande proyecto y me gustaria preguntarle si el host se apaga como puedo saber lo en homeassitant. gracias

**Comment by danielaradu2016** [comment]
Good night. first I wanted to thank you for the great project and I would like to ask you if the host goes out as I can know it in homeassitant. Thank you

**Comment by zewelor** [comment]
Thanks for suggestion, it was missed, it should have been there :D Happy new year !
