### ISSUE TITLE
Host dont report state offline in hassio

### ISSUE THREAD

**Issue by danielaradu2016** [zewelor/bt-mqtt-gateway#43]
Hy
Happy New Year
we have talk about the state of host for hassio and i change how you told me and i have this in bt-mqtt-gateway:

`mqtt:
  host: 192.168.x.xx
  port: 1883
  username: xxxx
  password: xxxx
  topic_prefix: hostname
  client_id: bt-mqtt-gateway
  availability_topic: lwt_topic `

` manager:
  topic_subscription:
    update_all:
      topic: homeassistant/status
      payload: online
  workers:
    miflora:
      args:
        devices:
          salonplant: xx:xx:xx:xx:xx:xx 
        topic_prefix: miflora
      update_interval: 300`
   
 `  mithermometer:
      args:
        devices:
          salon: xx:xx:xx:xx:xx:xx
          cocina: xx:xx:xx:xx:xx:xx
        topic_prefix: mithermometer
      update_interval: 120 `

and in hassio i have:
`mqtt:
  broker: 192.168.x.xx
  username: xxxxxx
  password: xxxxxx
  birth_message:
    topic: 'homeassistant/status'
    payload: 'online'
  discovery: true
  discovery_prefix: homeassistant`

sensor.yaml:
`- platform: mqtt
  state_topic: "hostname/mithermometer/salon/temperature"
  name: "Salon Temperatura"
  unit_of_measurement: "°C"
  icon_template: mdi:thermometer
  availability_topic: "hostname/lwt_topic"
  payload_available: "online"
  payload_not_available: "offline"

- platform: mqtt
  state_topic: "hostname/mithermometer/salon/humidity"
  name: "Salon Humidity"
  unit_of_measurement: "%"
  icon_template: mdi:water
  availability_topic: "hostname/lwt_topic"
  payload_available: "online"
  payload_not_available: "offline"

- platform: mqtt
  state_topic: "hostname/mithermometer/salon/battery"
  name: "Salon Battery"
  unit_of_measurement: "%"
  availability_topic: "hostname/lwt_topic"
  payload_available: "online"
  payload_not_available: "offline"`

I was change availability_topic: "hostname/lwt_topic"(and he work fine but when i shutdown the host i dont receive in hassio the state offline) with availability_topic: "hostname/lwt_topic/status"(dont work), and availability_topic: "lwt_topic/" dont work, availability_topic: "lwt_topic" .(dont work it means that the state the host in hassio is unavailable).

I check my mqtt and when i start bt-mqtt-gateway i see "hostname/lwt_topic online" and when i shutdown the host i se in mqtt "lwt topic offline" whitout "hostname". 

I was try with  ( payload_available: "hostname/lwt_topic") and (payload_not_available: "lwt topic") and is work but unchange state when i shutdown the host.

I think that i can make a automacion with mqtt publish but before i want to ask you if can check out again the mqtt.py program. I think that something happened in this program.
It will better if i made fresh install of mt-bt-gateway because i only change config.yaml and i just copy the new mqtt.py over the old mqtt.py and i restarted.

thanks a lot

**Comment by zewelor** [comment]
Please test this branch if everything works ok: mc-fix_lwt_topic_with_global_prefix
