### ISSUE TITLE
hci0 needs occasioanal reset

### ISSUE THREAD

**Issue by diplix** [zewelor/bt-mqtt-gateway#59]
from time to time bt-mqtt-gateway produces errors because the bluetooth interface on my rpi3 gets unresponsive.

```
Failed to execute management command 'scanend' (code: 11, error: Rejected)
Traceback (most recent call last):
  File "bt-mqtt-gateway/gateway.py", line 39, in <module>
    mqtt.publish(_WORKERS_QUEUE.get(block=True).execute())
  File "/home/pi/bt-mqtt-gateway/workers_manager.py", line 27, in execute
    messages = self._callback(*self._args)
  File "/home/pi/bt-mqtt-gateway/workers/toothbrush.py", line 28, in status_update
    devices = scanner.scan(5.0)
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 852, in scan
    self.start(passive=passive)
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 797, in start
    self._mgmtCmd(self._cmd()+"end")
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 312, in _mgmtCmd
    raise BTLEManagementError("Failed to execute management command '%s'" % (cmd), rsp)
bluepy.btle.BTLEManagementError: Failed to execute management command 'scanend' (code: 11, error: Rejected)

```

resetting the interface helps:
`sudo hciconfig hci0 reset`

i made this into a cron job that runs 4 times a day and since have no problems.

anyone else experiencing related problems? if so, could reseting the bluetooth interface on a schedule be included into python code of bt-mqtt-gateway?

**Comment by cybe** [comment]
This is usually caused by:
* Parallel access to the Bluetooth interface from another process
* Using the RPi Wifi interface in parallel
* Another Bluetooth client accessing the target device, like your smartphone

**Comment by zewelor** [comment]
What bluez version are you using ? For me default version for raspbian was unstable. After updating it works great. I think minimum stable version was 5.49 ( for rpi0 ).

**Comment by diplix** [comment]
```
pi@ivanka:~ $ bluetoothd -v 
5.43
```

followed https://scribles.net/updating-bluez-on-raspberry-pi-5-43-to-5-48/ to upgrade bluez to 5.49.

```
pi@ivanka:~ $ bluetoothctl -v
bluetoothctl: 5.49
```

i disabled my reset-cron and will see what happens …

**Comment by diplix** [comment]
had another bt lock, couldn’t even `hciconfig hci0 reset`, had unplug-reboot the pi. which bluez version do you use, @zewelor ? sure it’s 5.49?

**Comment by zewelor** [comment]
Currently I'm using 5.50. Before for many months 5.49.

**Comment by diplix** [comment]
downgraded back to the built-in raspbian bluez version, which handles `sudo hciconfig hci0 reset` more gracefully and overall runs more or less stable if i occasionally run the reset command.

**Comment by joselito11** [comment]
@diplix I have the same problems, can you please share the crone job config?

**Comment by diplix** [comment]
i moved bt-gateway to a nuc where it is working reliably. this is what i did on the pi:

`sudo crontab -e`
```
20 4 * * * hciconfig hci0 reset
20 10 * * * hciconfig hci0 reset
20 16 * * * hciconfig hci0 reset
20 22 * * * hciconfig hci0 reset
```

**Comment by joselito11** [comment]
Thaks, I am also on nuc
