### ISSUE TITLE
Support Xiaomi Mijia LYWSD02MMC Digital Hygrometer

### ISSUE THREAD

**Issue by plantoschka** [zewelor/bt-mqtt-gateway#71]
Please support this device. 

![1360074_1](https://user-images.githubusercontent.com/2125129/57232734-86d55080-701d-11e9-8505-e92ed88a654c.jpg)

I think it's nicer than the round version and also shows the time. This also work over bluetooth.

**Comment by zewelor** [comment]
Did you check if its supported already ? Maybe it has same api and just works ? If not thats the library currently used for thermometer, so support needs to be added there first https://github.com/hobbypunk90/mithermometer

**Comment by koenvervloesem** [comment]
Isn't this fixed by https://github.com/zewelor/bt-mqtt-gateway/pull/116?
