### ISSUE TITLE
Docker: multiarch build

### ISSUE THREAD

**Issue by hobbypunk90** [zewelor/bt-mqtt-gateway#78]
**Is your feature request related to a problem? Please describe.**

the generated docker image runs only on amd64 systems.

**Describe the solution you'd like**
we need a build for aarch64 and armv7 to support raspberry pis.

**Additional context**
i never tried multiarch builds, but i'll read through and try to create it "soon"😅

**Comment by krasnoukhov** [comment]
@zewelor I couldn't find any build configuration in the repo, do you mind sharing how it's currently configured?

**Comment by zewelor** [comment]
There is only configuration at docker hub, to auto build after each commit. It uses Dockerfile from repo.

**Comment by zewelor** [comment]
I think we can close this as there is basic setup for multiarch build

**Comment by krasnoukhov** [comment]
Yes, I believe `arm64v8` could be easily added as soon there's need
