### ISSUE TITLE
Example configuration for homeassistant

### ISSUE THREAD

**Issue by rytilahti** [zewelor/bt-mqtt-gateway#8]
Would it be possible to get a basic configuration for climate & miflora components for homeassistant, e.g. how to let homeassistant autodiscover the sensors?

**Comment by bbbenji** [comment]
Unfortunately, there is no auto-discovery yet... Climate isn't supported anyway. [(See here)](https://www.home-assistant.io/docs/mqtt/discovery/)
Hoping sensor auto-discovery is implemented soon.

However you can take a look at my basic hass config for these devices here: 
https://gist.github.com/bbbenji/78dee256ae715dc669923551b4e6aab3
