### ISSUE TITLE
OralB history

### ISSUE THREAD

**Issue by joselito11** [zewelor/bt-mqtt-gateway#86]
Will be possible to pull history data from OralB toothbrush? Like it does in OralB app. Toothbrush saves cca 30 sessions.

**Comment by zewelor** [comment]
If the app gets that history it should be possible. I don't have that toothbrush, it should be possible to reverse app or protocol and find how to read it. Maybe there is protocol reverse done already, so it could be implemented here.

**Comment by joselito11** [comment]
Great!
