### ISSUE TITLE
[Solved] Miscale profile

### ISSUE THREAD

**Issue by dckiller51** [zewelor/bt-mqtt-gateway#98]
Hello, thank you this antenna ble. 
I come from Jeedom where there is the same antenna. [https://github.com/jeedom/plugin-blea/tree/beta/resources/blead/devices]

Do you have the option to add profiles for the scale so that it detects the user. 

For example, I weigh 69Kg, my son 40Kg and my wife 60Kg. So according to the weight one comes to inform an input_boolean according to the person who weighs himself. It exists on this page ([https://github.com/jeedom/plugin-blea/blob/beta/resources/blead/devices/miscale.py]) but it is too complex for me.

**Comment by zewelor** [comment]
For me it looks like Home Assistant responsibility, to parse and act on received data.

**Comment by dckiller51** [comment]
Hello, ok I see how to do but I can not do it.


I can not write the formula

`-` platform: template
    sensors:
       weight_aurelien:
          friendly_name: "Weight Aurélien"
            value_template: >-
              {% if is_state("states.sensor.miscale") %}
                  {{ float < 68 | (states.sensor.weight_aurelien.state) | float > 72 }}
              {% endif %}``

**Comment by zewelor** [comment]
Cool, I've added this to wiki https://github.com/zewelor/bt-mqtt-gateway/wiki/Home-Assistant#for-monitoring-different-people-weight . Also I think you don't need to declare template sensor platform 2 times. From docs it looks like you can declare many sensor, via single platform template sensor entry ( https://www.home-assistant.io/components/template/ )
